---
- hosts: lb
  remote_user: user
  become: yes
  gather_facts: no
  tasks:
    - name: Create VM if needed
      include_role:
        name: vm
      when: create_vm

    - name: Add VM DNS records
      include_role:
        name: dns

    - name: Gather facts
      gather_facts:

    - name: Role LoadBalancer
      include_role:
        name: lb
        tasks_from: nginx
      when: item.value.lbapp == "nginx"
      loop: "{{ lookup('dict', servers, wantlist=true) }}"

    - name: Add DNS records
      include_role:
        name: dns
        tasks_from: custom
      vars:
        record: "{{ dns.value.url }}"
      loop: "{{ lookup('dict', upstreams, wantlist=true) }}"
      loop_control:
        loop_var: dns

    - name: Enable and settings ufw
      include_role:
        name: ufw
      vars:
        ports:
          - 80
          - 443
          - 22
