---
- hosts: webservers
  remote_user: user
  become: yes
  gather_facts: no
  tasks:
    - name: Create VM if needed
      include_role:
        name: vm
      when: create_vm

    - name: Add DNS records
      include_role:
        name: dns

    - name: Gather facts
      gather_facts:

    - name: Role webserver
      include_role:
        name: webserver

    - name: Enable and settings ufw
      include_role:
        name: ufw
      vars:
        ports:
          - 80
          - 443
          - 22
