---
- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "/tmp/{{ filename }}.key"
  delegate_to: localhost

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "/tmp/{{ filename }}.csr"
    privatekey_path: "/tmp/{{ filename }}.key"
    common_name: "{{ cname }}"
  delegate_to: localhost

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "/tmp/{{ filename }}.crt"
    privatekey_path: "/tmp/{{ filename }}.key"
    csr_path: "/tmp/{{ filename }}.csr"
    provider: selfsigned
  delegate_to: localhost
