---
- name: Add DNS Records
  lineinfile:
    path: /etc/bind/master-zones/infra.test
    insertafter: EOF
    line: '{{ item.value.vmname }}                           IN              A               {{ item.value.ip }}'
  loop: "{{ lookup('dict', servers, wantlist=True) }}"
  delegate_to: 192.168.100.2
  no_log: true
  run_once: true

- name: Add PTR Records
  lineinfile:
    path: /etc/bind/db.100
    insertafter: EOF
    line: '{{ item.value.ip | ansible.utils.ipaddr("revdns") }}                           IN              PTR               {{ item.value.vmname }}.{{ item.value.domain }}.'
  loop: "{{ lookup('dict', servers, wantlist=True) }}"
  delegate_to: 192.168.100.2
  no_log: true
  run_once: true

- name: Reload configuration BIND
  service:
    name: bind9
    state: reloaded
  delegate_to: 192.168.100.2
  run_once: true
