---
- name: Start nginx
  service:
    name: nginx
    state: started

- name: Stop nginx
  service:
    name: nginx
    state: stopped

- name: Restart nginx
  service:
    name: nginx
    state: restarted
